# Generated by Django 5.0.2 on 2024-05-19 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customuser_is_superuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
